### ISSUE TITLE
Starting

### ISSUE THREAD

**Issue by RidaGaming** [bouletmarc/PokeBot-GenerationII#1]
When the Pokemon Professor at the Start asks if you wnat to help him it always clicks "No"

**Comment by bouletmarc** [comment]
im closing issue since this pokebot are not even finished, I dont even know why you are posting issue while this project arent even done to like 10% -,-' im not working on this since a Long time, it was only to show that GenII can run under Pokebot, it wasnt really intended to make a full run out of it

**Comment by MercenaryGreil** [comment]
Here is the fix I shared in open issues: 

Go to PokeBot-GenerationII-master > PokeBot-GenerationII-master > action > textbox.lua

After opening the textbox.lua scroll all the way down to where you find the line about "function Textbox.handle"

From that first line to "end" remove and replace with the following:

function Textbox.handle()
if not Textbox.isActive() then
return true
end
Input.cancel()
end

PS: Make sure you do not remove the "return Textbox" line at the very bottom.
